import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  hi: {
    'common.login': 'लॉगिन',
    'common.logout': 'लॉगआउट',
    'common.register': 'पंजीकरण करें',
    'common.home': 'होम',
    'common.ramWriting': 'राम नाम लेखन',
    'common.pledge': 'संकल्प',
    'common.dailySadhana': 'दैनिक साधना',
    'common.seva': 'सेवा',
    'common.events': 'कार्यक्रम',
    'common.gallery': 'गैलरी',
    'common.contact': 'संपर्क',
    'common.mySadhana': 'मेरी साधना',
    'common.loading': 'लोड हो रहा है...',
    'header.mantra': '॥ श्री राम जय राम जय जय राम ॥',
    'header.brand': 'श्री राम नाम लेखन अभियान',
    'header.subtitle': 'बाबा नीम करौली महाराज की प्रेरणा से',
    'header.menu': 'मेनू',
    'header.writeRam': 'राम नाम लिखें',
    'header.devotion': 'भक्ति • साधना • सेवा',
    'hero.eyebrow': 'बाबा नीम करौली महाराज की प्रेरणा से',
    'hero.title': 'राम नाम लिखें,\nजीवन में भक्ति और सकारात्मकता को स्थान दें',
    'hero.description': 'प्रतिदिन कुछ समय प्रभु श्री राम को समर्पित करें। राम नाम लेखन, नाम-स्मरण, साधना और सेवा की इस सकारात्मक यात्रा से जुड़ें।',
    'hero.start': 'राम नाम लिखना शुरू करें',
    'hero.takePledge': 'राम नाम का संकल्प लें',
    'stats.devotees': 'जुड़े साधक',
    'stats.today': 'आज लिखे गए राम नाम',
    'stats.month': 'इस माह के राम नाम',
    'stats.total': 'कुल लिखे गए राम नाम',
    'stats.world': 'देश / विश्व',
    'stats.indiaWorld': 'भारत + विश्व',
    'about.kicker': 'हमारे अभियान का उद्देश्य',
    'about.title': 'राम नाम लेखन • नाम-स्मरण • साधना • सेवा',
    'about.description': 'राम नाम लेखन मन को एकाग्र करने और भक्ति से जोड़ने का सरल माध्यम है। हमारा उद्देश्य अधिक से अधिक लोगों को नियमित साधना, सामूहिक भक्ति और सेवा से जोड़ना है।',
    'about.daily': 'प्रतिदिन राम नाम लिखें',
    'about.seva': 'सेवा कार्यों से जुड़ें',
    'about.pledge': 'नियमित संकल्प निभाएं',
    'about.share': 'अनुभव साझा करें',
    'writer.dashboardTitle': '🙏 मेरी साधना Dashboard',
    'writer.onPage': 'इस पृष्ठ पर',
    'writer.todayDeposited': 'आज जमा',
    'writer.totalDeposited': 'कुल जमा',
    'writer.remaining': 'पृष्ठ में शेष',
    'writer.continue': 'श्री राम लिखना जारी रखें',
    'writer.pageTitle': 'राम नाम लेखन — 108 नाम का पृष्ठ',
    'writer.instructionStrong': 'English keyboard से RAM या SHRI RAM लिखें।',
    'writer.instructionSub': 'English में टाइप होगा लेकिन स्क्रीन पर हिन्दी में राम नाम दिखाई देगा।',
    'writer.activeBox': 'सक्रिय खाना',
    'writer.pageCount': 'पृष्ठ गणना',
    'writer.write': 'लिखें',
    'writer.or': 'या',
    'writer.undo': 'पिछला अक्षर',
    'writer.clearCell': 'खाना साफ करें',
    'writer.reset': 'पूरा पृष्ठ रीसेट',
    'writer.autoCount': 'स्वतः गिनती',
    'writer.depositing': 'जमा हो रहा है...',
    'writer.deposit': '{count} राम नाम साधना में जमा करें',
    'writer.inspiration': '🏆 प्रेरणा सूची',
    'writer.devoteeA': 'भक्त अ',
    'writer.devoteeB': 'भक्त ब',
    'writer.devoteeC': 'भक्त स',
    'writer.devoteeD': 'भक्त द',
    'writer.devoteeE': 'भक्त इ',
    'writer.notCompetition': 'यह प्रतियोगिता नहीं, एक-दूसरे को प्रेरित करने का माध्यम है।',
    'writer.completedPage': '🙏 108 राम नाम का पृष्ठ पूरा हो गया। अब “साधना में जमा करें” दबाएँ।',
    'writer.startHint': 'राम लिखने के लिए R दबाएँ या श्री राम लिखने के लिए S दबाएँ।',
    'writer.nextLetter': 'अगला अक्षर "{letter}" लिखें।',
    'writer.copyBlocked': 'कॉपी-पेस्ट की अनुमति नहीं है। कृपया राम नाम स्वयं लिखें।',
    'writer.copyBlockedEach': 'कॉपी-पेस्ट की अनुमति नहीं है। कृपया प्रत्येक राम नाम स्वयं लिखें।',
    'writer.dropBlocked': 'Drag & Drop की अनुमति नहीं है। कृपया राम नाम स्वयं लिखें।',
    'writer.pageCleared': 'पृष्ठ साफ कर दिया गया।',
    'writer.loginToDeposit': 'साधना जमा करने के लिए पहले लॉगिन करें।',
    'writer.writeAtLeastOne': 'पहले कम से कम एक पूरा राम नाम लिखें।',
    'writer.deposited': '🙏 {count} राम नाम आपकी साधना में जमा हो गए।',
    'writer.depositFailed': 'अभी साधना जमा नहीं हो पाई।',
    'writer.aria': 'राम नाम {number}',
    'pledge.kicker': 'राम नाम संकल्प',
    'pledge.title': 'एक संकल्प — नियमित साधना की ओर',
    'pledge.description': 'अपनी सुविधा और श्रद्धा के अनुसार लक्ष्य चुनें। संख्या से अधिक महत्वपूर्ण नियमितता और भाव है।',
    'pledge.days': 'दिन',
    'pledge.lakh': 'लाख',
    'pledge.cardLabel': 'राम नाम संकल्प',
    'pledge.take': 'संकल्प लें →',
    'pledge.loginFirst': 'संकल्प लेने के लिए पहले लॉगिन करें।',
    'pledge.success': 'संकल्प सफल। आपका Sankalp ID: {id}',
    'pledge.failed': 'संकल्प सेव नहीं हो पाया।',
    'pledge.title11': '11 दिन का संकल्प',
    'pledge.title21': '21 दिन का संकल्प',
    'pledge.title40': '40 दिन का संकल्प',
    'pledge.title108': '108 दिन का संकल्प',
    'pledge.title1L': '1 लाख राम नाम',
    'pledge.title11L': '11 लाख राम नाम',
    'sadhana.kicker': 'दैनिक साधना',
    'sadhana.title': 'हर दिन भक्ति के लिए कुछ समय',
    'sadhana.ramNaam': 'श्री राम नाम',
    'sadhana.hanumanChalisa': 'हनुमान चालीसा',
    'sadhana.mantra': 'राम मंत्र-जाप',
    'sadhana.sundarkand': 'सुंदरकांड पाठ',
    'sadhana.bhajan': 'भजन एवं ध्यान',
    'events.today': '📅 आज के कार्यक्रम',
    'events.groupWriting': 'सामूहिक राम नाम लेखन',
    'events.sundarkand': 'सुंदरकांड पाठ',
    'events.hanumanChalisa': 'हनुमान चालीसा पाठ',
    'events.morning': 'सुबह 06:00 - 08:00',
    'events.afternoon': 'दोपहर 03:00 - 05:00',
    'events.evening': 'शाम 07:00 - 08:00',
    'events.online': 'ऑनलाइन',
    'events.sep': 'सित.',
    'seva.kicker': 'भक्ति से सेवा तक',
    'seva.title': 'सेवा के हमारे संकल्प',
    'seva.description': 'राम नाम के साथ सामाजिक और पर्यावरणीय सेवा से जुड़ें।',
    'seva.food': 'अन्न सेवा',
    'seva.education': 'शिक्षा सेवा',
    'seva.medical': 'चिकित्सा सहायता',
    'seva.trees': 'वृक्षारोपण',
    'seva.other': 'अन्य सेवा',
    'seva.contribute': 'सेवा में योगदान दें',
    'media.bhajan': 'भजन एवं कीर्तन',
    'media.spiritual': 'राम नाम संकीर्तन एवं आध्यात्मिक सामग्री',
    'media.viewBhajan': 'सभी भजन देखें',
    'media.experience': 'भक्त अनुभव',
    'media.quote': '“राम नाम लेखन ने मेरे दिन में शांति, अनुशासन और सकारात्मकता का एक नया भाव जोड़ा।”',
    'media.devoteeDelhi': '— एक साधक, दिल्ली',
    'media.viewExperiences': 'सभी अनुभव देखें',
    'media.gallery': 'गैलरी',
    'media.viewMedia': 'चित्र एवं वीडियो देखें',
    'media.news': 'समाचार / अपडेट',
    'media.news1': 'राम नाम लेखन अभियान से जुड़ें',
    'media.news1sub': '12,000+ साधक सामूहिक साधना से जुड़े',
    'media.news2': 'सामूहिक सुंदरकांड कार्यक्रम',
    'media.news2sub': 'आगामी रविवार • ऑनलाइन',
    'media.viewNews': 'सभी समाचार देखें',
    'home.message': '🌸 आज का संदेश',
    'home.quote': '“राम नाम को अपने दिन का एक छोटा, लेकिन नियमित हिस्सा बनाइए।”',
    'home.quoteSub': '11 राम नाम से शुरुआत करें, 108 राम नाम का संकल्प लें या अपना बड़ा लक्ष्य निर्धारित करें।',
    'home.takePledge': 'संकल्प लें',
    'footer.title': 'श्री राम नाम लेखन अभियान',
    'footer.description': 'राम नाम, भक्ति, साधना और सेवा से जुड़ने का डिजिटल मंच।',
    'footer.tagline': 'राम नाम लिखें • राम नाम जपें • सेवा से जुड़ें',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.importantLinks': 'महत्वपूर्ण लिंक',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'नियम एवं शर्तें',
    'footer.disclaimer': 'अस्वीकरण',
    'footer.contactUs': 'संपर्क करें',
    'footer.address': '📍 पता: ____________________',
    'footer.phone': '📞 फोन: ____________________',
    'footer.email': '📧 ईमेल: info@ramnaamabhiyan.com',
    'footer.copyright': '© 2026 श्री राम नाम लेखन अभियान • सभी अधिकार सुरक्षित',
    'auth.welcome': '🙏 स्वागत है',
    'auth.loginTitle': 'साधक लॉगिन',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.loginButton': 'लॉगिन करें',
    'auth.loginFailed': 'लॉगिन नहीं हो पाया।',
    'auth.newAccount': 'नया खाता?',
    'auth.join': '🌺 अभियान से जुड़ें',
    'auth.registerTitle': 'साधक पंजीकरण',
    'auth.fullName': 'पूरा नाम',
    'auth.mobile': 'मोबाइल',
    'auth.city': 'शहर',
    'auth.state': 'राज्य',
    'auth.country': 'देश',
    'auth.india': 'भारत',
    'auth.registerFailed': 'पंजीकरण नहीं हो पाया।',
    'auth.existing': 'पहले से खाता है?',
    'dashboard.kicker': '🙏 मेरी साधना',
    'dashboard.progress': '{name}, आपकी आध्यात्मिक प्रगति',
    'dashboard.today': 'आज',
    'dashboard.total': 'कुल',
    'dashboard.currentStreak': 'वर्तमान स्ट्रीक',
    'dashboard.longestStreak': 'सबसे लंबी स्ट्रीक',
    'dashboard.days': '{count} दिन',
    'dashboard.myPledges': 'मेरे संकल्प',
    'dashboard.sankalpId': 'Sankalp ID',
    'dashboard.noPledge': 'अभी कोई सक्रिय संकल्प नहीं है। होम पेज से संकल्प लें।',
    'admin.panel': 'Admin Panel',
    'admin.title': 'अभियान प्रबंधन',
    'admin.totalUsers': 'कुल साधक',
    'admin.totalRam': 'कुल राम नाम',
    'admin.todayRam': 'आज के राम नाम',
    'admin.activePledges': 'सक्रिय संकल्प',
    'admin.upcomingEvents': 'आगामी कार्यक्रम',
    'admin.pendingExperiences': 'लंबित अनुभव',
    'admin.modules': 'Admin Modules',
    'admin.userManagement': 'User Management',
    'admin.verification': 'Ram Naam Verification',
    'admin.pledgeManagement': 'Pledge Management',
    'admin.events': 'Events',
    'admin.sadhanaCms': 'Daily Sadhana CMS',
    'admin.gallery': 'Gallery',
    'admin.news': 'News / Blog',
    'admin.certificates': 'Certificates',
    'admin.volunteer': 'Volunteer / Seva',
    'admin.audit': 'Audit Logs'
  },
  en: {
    'common.login': 'Login',
    'common.logout': 'Logout',
    'common.register': 'Register',
    'common.home': 'Home',
    'common.ramWriting': 'Ram Naam Writing',
    'common.pledge': 'Pledge',
    'common.dailySadhana': 'Daily Sadhana',
    'common.seva': 'Seva',
    'common.events': 'Events',
    'common.gallery': 'Gallery',
    'common.contact': 'Contact',
    'common.mySadhana': 'My Sadhana',
    'common.loading': 'Loading...',
    'header.mantra': '॥ Shri Ram Jai Ram Jai Jai Ram ॥',
    'header.brand': 'Shri Ram Naam Writing Campaign',
    'header.subtitle': 'Inspired by Baba Neem Karoli Maharaj',
    'header.menu': 'Menu',
    'header.writeRam': 'Write Ram Naam',
    'header.devotion': 'Devotion • Sadhana • Seva',
    'hero.eyebrow': 'Inspired by Baba Neem Karoli Maharaj',
    'hero.title': 'Write Ram Naam,\nmake space for devotion and positivity in life',
    'hero.description': 'Dedicate a little time every day to Lord Shri Ram. Join this positive journey of Ram Naam writing, remembrance, spiritual practice, and service.',
    'hero.start': 'Start Writing Ram Naam',
    'hero.takePledge': 'Take a Ram Naam Pledge',
    'stats.devotees': 'Devotees Joined',
    'stats.today': 'Ram Naam Written Today',
    'stats.month': 'Ram Naam This Month',
    'stats.total': 'Total Ram Naam Written',
    'stats.world': 'Country / World',
    'stats.indiaWorld': 'India + World',
    'about.kicker': 'Purpose of Our Campaign',
    'about.title': 'Ram Naam Writing • Remembrance • Sadhana • Seva',
    'about.description': 'Writing Ram Naam is a simple way to focus the mind and connect with devotion. Our purpose is to connect more people with regular spiritual practice, collective devotion, and service.',
    'about.daily': 'Write Ram Naam Daily',
    'about.seva': 'Join Seva Activities',
    'about.pledge': 'Keep a Regular Pledge',
    'about.share': 'Share Your Experience',
    'writer.dashboardTitle': '🙏 My Sadhana Dashboard',
    'writer.onPage': 'On This Page',
    'writer.todayDeposited': 'Deposited Today',
    'writer.totalDeposited': 'Total Deposited',
    'writer.remaining': 'Remaining on Page',
    'writer.continue': 'Continue Writing Shri Ram',
    'writer.pageTitle': 'Ram Naam Writing — Page of 108 Names',
    'writer.instructionStrong': 'Use the English keyboard to type RAM or SHRI RAM.',
    'writer.instructionSub': 'You type in English, while the screen displays the Ram Naam in Hindi.',
    'writer.activeBox': 'Active Box',
    'writer.pageCount': 'Page Count',
    'writer.write': 'Type',
    'writer.or': 'or',
    'writer.undo': 'Previous Letter',
    'writer.clearCell': 'Clear Box',
    'writer.reset': 'Reset Full Page',
    'writer.autoCount': 'Auto Count',
    'writer.depositing': 'Depositing...',
    'writer.deposit': 'Deposit {count} Ram Naam into Sadhana',
    'writer.inspiration': '🏆 Inspiration Board',
    'writer.devoteeA': 'Devotee A',
    'writer.devoteeB': 'Devotee B',
    'writer.devoteeC': 'Devotee C',
    'writer.devoteeD': 'Devotee D',
    'writer.devoteeE': 'Devotee E',
    'writer.notCompetition': 'This is not a competition; it is a way to inspire one another.',
    'writer.completedPage': '🙏 The page of 108 Ram Naam is complete. Now press “Deposit into Sadhana”.',
    'writer.startHint': 'Press R to write Ram or S to write Shri Ram.',
    'writer.nextLetter': 'Type the next letter "{letter}".',
    'writer.copyBlocked': 'Copy-paste is not allowed. Please write Ram Naam yourself.',
    'writer.copyBlockedEach': 'Copy-paste is not allowed. Please write each Ram Naam yourself.',
    'writer.dropBlocked': 'Drag & Drop is not allowed. Please write Ram Naam yourself.',
    'writer.pageCleared': 'The page has been cleared.',
    'writer.loginToDeposit': 'Please log in before depositing your Sadhana.',
    'writer.writeAtLeastOne': 'Please write at least one complete Ram Naam first.',
    'writer.deposited': '🙏 {count} Ram Naam have been deposited into your Sadhana.',
    'writer.depositFailed': 'Your Sadhana could not be deposited right now.',
    'writer.aria': 'Ram Naam {number}',
    'pledge.kicker': 'Ram Naam Pledge',
    'pledge.title': 'One Pledge — Towards Regular Sadhana',
    'pledge.description': 'Choose a goal according to your convenience and devotion. Regularity and sincerity matter more than the number.',
    'pledge.days': 'Days',
    'pledge.lakh': 'Lakh',
    'pledge.cardLabel': 'Ram Naam Pledge',
    'pledge.take': 'Take Pledge →',
    'pledge.loginFirst': 'Please log in before taking a pledge.',
    'pledge.success': 'Pledge created successfully. Your Sankalp ID: {id}',
    'pledge.failed': 'The pledge could not be saved.',
    'pledge.title11': '11-Day Pledge',
    'pledge.title21': '21-Day Pledge',
    'pledge.title40': '40-Day Pledge',
    'pledge.title108': '108-Day Pledge',
    'pledge.title1L': '1 Lakh Ram Naam',
    'pledge.title11L': '11 Lakh Ram Naam',
    'sadhana.kicker': 'Daily Sadhana',
    'sadhana.title': 'A Little Time for Devotion Every Day',
    'sadhana.ramNaam': 'Shri Ram Naam',
    'sadhana.hanumanChalisa': 'Hanuman Chalisa',
    'sadhana.mantra': 'Ram Mantra Japa',
    'sadhana.sundarkand': 'Sundarkand Recitation',
    'sadhana.bhajan': 'Bhajan & Meditation',
    'events.today': '📅 Today’s Events',
    'events.groupWriting': 'Collective Ram Naam Writing',
    'events.sundarkand': 'Sundarkand Recitation',
    'events.hanumanChalisa': 'Hanuman Chalisa Recitation',
    'events.morning': '06:00 AM - 08:00 AM',
    'events.afternoon': '03:00 PM - 05:00 PM',
    'events.evening': '07:00 PM - 08:00 PM',
    'events.online': 'Online',
    'events.sep': 'Sep',
    'seva.kicker': 'From Devotion to Seva',
    'seva.title': 'Our Commitments to Seva',
    'seva.description': 'Connect Ram Naam with social and environmental service.',
    'seva.food': 'Food Seva',
    'seva.education': 'Education Seva',
    'seva.medical': 'Medical Support',
    'seva.trees': 'Tree Plantation',
    'seva.other': 'Other Seva',
    'seva.contribute': 'Contribute to Seva',
    'media.bhajan': 'Bhajan & Kirtan',
    'media.spiritual': 'Ram Naam Sankirtan and spiritual content',
    'media.viewBhajan': 'View All Bhajans',
    'media.experience': 'Devotee Experiences',
    'media.quote': '“Writing Ram Naam brought a new sense of peace, discipline, and positivity to my day.”',
    'media.devoteeDelhi': '— A devotee, Delhi',
    'media.viewExperiences': 'View All Experiences',
    'media.gallery': 'Gallery',
    'media.viewMedia': 'View Photos & Videos',
    'media.news': 'News / Updates',
    'media.news1': 'Join the Ram Naam Writing Campaign',
    'media.news1sub': '12,000+ devotees connected through collective Sadhana',
    'media.news2': 'Collective Sundarkand Program',
    'media.news2sub': 'Coming Sunday • Online',
    'media.viewNews': 'View All News',
    'home.message': '🌸 Today’s Message',
    'home.quote': '“Make Ram Naam a small but regular part of your day.”',
    'home.quoteSub': 'Start with 11 Ram Naam, take a pledge for 108, or set a larger personal goal.',
    'home.takePledge': 'Take a Pledge',
    'footer.title': 'Shri Ram Naam Writing Campaign',
    'footer.description': 'A digital platform for Ram Naam, devotion, Sadhana, and Seva.',
    'footer.tagline': 'Write Ram Naam • Chant Ram Naam • Join Seva',
    'footer.quickLinks': 'Quick Links',
    'footer.importantLinks': 'Important Links',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.disclaimer': 'Disclaimer',
    'footer.contactUs': 'Contact Us',
    'footer.address': '📍 Address: ____________________',
    'footer.phone': '📞 Phone: ____________________',
    'footer.email': '📧 Email: info@ramnaamabhiyan.com',
    'footer.copyright': '© 2026 Shri Ram Naam Writing Campaign • All Rights Reserved',
    'auth.welcome': '🙏 Welcome',
    'auth.loginTitle': 'Devotee Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loginButton': 'Login',
    'auth.loginFailed': 'Unable to log in.',
    'auth.newAccount': 'New account?',
    'auth.join': '🌺 Join the Campaign',
    'auth.registerTitle': 'Devotee Registration',
    'auth.fullName': 'Full Name',
    'auth.mobile': 'Mobile',
    'auth.city': 'City',
    'auth.state': 'State',
    'auth.country': 'Country',
    'auth.india': 'India',
    'auth.registerFailed': 'Registration failed.',
    'auth.existing': 'Already have an account?',
    'dashboard.kicker': '🙏 My Sadhana',
    'dashboard.progress': '{name}, your spiritual progress',
    'dashboard.today': 'Today',
    'dashboard.total': 'Total',
    'dashboard.currentStreak': 'Current Streak',
    'dashboard.longestStreak': 'Longest Streak',
    'dashboard.days': '{count} days',
    'dashboard.myPledges': 'My Pledges',
    'dashboard.sankalpId': 'Sankalp ID',
    'dashboard.noPledge': 'There is no active pledge yet. Take one from the home page.',
    'admin.panel': 'Admin Panel',
    'admin.title': 'Campaign Management',
    'admin.totalUsers': 'Total Devotees',
    'admin.totalRam': 'Total Ram Naam',
    'admin.todayRam': 'Ram Naam Today',
    'admin.activePledges': 'Active Pledges',
    'admin.upcomingEvents': 'Upcoming Events',
    'admin.pendingExperiences': 'Pending Experiences',
    'admin.modules': 'Admin Modules',
    'admin.userManagement': 'User Management',
    'admin.verification': 'Ram Naam Verification',
    'admin.pledgeManagement': 'Pledge Management',
    'admin.events': 'Events',
    'admin.sadhanaCms': 'Daily Sadhana CMS',
    'admin.gallery': 'Gallery',
    'admin.news': 'News / Blog',
    'admin.certificates': 'Certificates',
    'admin.volunteer': 'Volunteer / Seva',
    'admin.audit': 'Audit Logs'
  }
};

function interpolate(template, variables = {}) {
  return Object.entries(variables).reduce(
    (text, [key, value]) => text.replaceAll(`{${key}}`, String(value)),
    template
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('ramNaamLanguage') || 'hi');

  useEffect(() => {
    localStorage.setItem('ramNaamLanguage', language);
    document.documentElement.lang = language === 'hi' ? 'hi' : 'en';
  }, [language]);

  const value = useMemo(() => {
    const t = (key, variables) => interpolate(translations[language]?.[key] ?? translations.hi[key] ?? key, variables);
    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'hi' ? 'en' : 'hi')),
      t,
      locale: language === 'hi' ? 'hi-IN' : 'en-IN'
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
